version: "3.9"

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
  web:
    build: .
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=postgres
      - GEMINI_API_KEY= <CHAVE API>
      - postgres

  app:
    build: .
    container_name: backend_shopper
    ports:
      - 3000:3000    
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database