version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: db_shopper
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mydb
  web:
    build: .
    ports:
      - 3001:3000
    environment:
      - POSTGRES_HOST=postgres
      - GEMINI_API_KEY= <CHAVE API>
      - postgres
